"""亮色主题常量：圆角、间距、主色（参考现代弹窗风格）"""
# 圆角（略大以便抗锯齿后弧线更顺滑）
CARD_RADIUS = 12
INPUT_RADIUS = 10
BTN_RADIUS = 10
# 背景
BG_MAIN = "#f0f2f5"
BG_CARD = "#ffffff"
BG_NAV = "#ffffff"
INPUT_BG = "#fafafa"
# 边框 / 分割（输入框、下拉框包裹层用稍粗边框，圆角处更清晰）
BORDER_COLOR = "#e5e7eb"
INPUT_BORDER_WIDTH = 2
OPTION_MENU_INNER_RADIUS = INPUT_RADIUS - INPUT_BORDER_WIDTH
# 主色（按钮、强调）
ACCENT = "#2563eb"
ACCENT_HOVER = "#1d4ed8"
# 次要按钮（幽灵）
BTN_SECONDARY_FG = "transparent"
BTN_SECONDARY_BORDER = "#d1d5db"
BTN_SECONDARY_TEXT = "#374151"
BTN_SECONDARY_HOVER = "#f3f4f6"
# 导航当前项
NAV_ACTIVE_FG = "#eff6ff"
NAV_ACTIVE_TEXT = "#1d4ed8"
# 下拉框（与输入框一致的表单风格）
OPTION_MENU_FG = INPUT_BG
OPTION_MENU_BUTTON = BORDER_COLOR
OPTION_MENU_BUTTON_HOVER = BTN_SECONDARY_HOVER
OPTION_MENU_DROPDOWN_FG = BG_CARD
OPTION_MENU_DROPDOWN_HOVER = BTN_SECONDARY_HOVER

# 文字
TEXT_HEADING = "#111827"
TEXT_BODY = "#374151"
TEXT_MUTED = "#6b7280"
